# Generated by Django 3.2.8 on 2021-10-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanks_1', models.TextField()),
                ('thanks_2', models.TextField()),
                ('thanks_3', models.TextField()),
                ('done_good_1', models.TextField()),
                ('done_good_2', models.TextField()),
                ('done_good_3', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
